SmartPurchase/urls.py
from django.contrib import admin
from django.urls import path, include
from . import Vistas

urlpatterns = [
    path(r'', include('desarrolloSmartApp.urls')),
    path(r'admin/', admin.site.urls),
    path(r'', Vistas.hellow_world),
]

desarrolloSmartApp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(r'desarrolloSmartApp/Registro.html', views.paginaRegistro),
    path(r'desarrolloSmartApp/registro', views.registro),
    path(r'desarrolloSmartApp/Principal.html', views.login),
    path(r'desarrolloSmartApp/', views.principal),
    path(r'desarrolloSmartApp/index.html', views.paginaLogin),
    path(r'desarrolloSmartApp/NuevaCompra.html',views.nuevaCompra),
    path(r'desarrolloSmartApp/TerminarCompra.html',views.terminarCompra),
    path(r'desarrolloSmartApp/TarjDebitoCredito.html',views.tarjeta),
    path(r'desarrolloSmartApp/comprasHistorico.html',views.comprasHistorico),
    path(r'tarjeta/',views.tarjDebitoCredito)
]

desarrolloSmartApp/models.py
from django.db import models


#TABLA USUARIO
class Usuario(models.Model):
    nombre=models.CharField(max_length= 255)
    apellido=models.CharField(max_length= 255)
    seleccionSexo=models.CharField(max_length= 255)
    nacimiento=models.DateField()
    barrio=models.CharField(max_length= 255)
    direccion=models.CharField(max_length= 255)
    email=models.EmailField(unique = True)
    contrasena=models.CharField(max_length= 255)

    def __str__(self):
        return self.nombre
    

#TABLA COMPRA
class Compra(models.Model):
    idUsuario=models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha=models.DateTimeField(auto_now_add=True, auto_now = False)
    monto_compra=models.IntegerField()
   


#TABLA CATEGORIA
class Categoria(models.Model):
    nombreCategoria=models.CharField(max_length= 255)

#TABLA CATEGORIA
class SubCategoria(models.Model):
    idCategoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombreCategoria=models.CharField(max_length= 255)
    

#TABLA PRODUCTO
class Producto(models.Model):
    nombre=models.CharField(max_length= 255)
    precio=models.IntegerField()
    marca=models.CharField(max_length= 255)
    idSubCategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='static/diseñoSmart/imagenes/ImagenesCatalogo')
    

#TABLA Item
class Item(models.Model):
    idCompra=models.ForeignKey(Compra, on_delete=models.CASCADE)
    idProducto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad=models.IntegerField()
    precioUnitario=models.IntegerField()
    
    def __eq__(self, other): 
        if isinstance(other, Item): 
            return self.idCompra == other.idCompra
        return NotImplemented
    

#TABLA SUPERMERCADO
class Supermercado(models.Model):
    nombre=models.CharField(max_length= 255)
    direccion=models.CharField(max_length= 255)
    horario=models.CharField(max_length= 255)
    telefono=models.IntegerField()
    

#TABLA PRODUCTOS_SUPERMERCADO
class Producto_Supermercado(models.Model):
    idProducto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    idSupermercado=models.ForeignKey(Supermercado, on_delete=models.CASCADE)

#TABLA TARJETA
class Tarjeta(models.Model):
    tipo=models.CharField(max_length= 255)
    titular=models.CharField(max_length= 255)
    num=models.IntegerField()
    cod=models.IntegerField()
    vencimiento=models.DateField()
    

desarrolloSmartApp/forms.py
from django import forms
from .models import *


class formLoginUsuario(forms.Form):
    usuario = forms.CharField(max_length=100)


class formLoginContrasena(forms.Form):
    contraseña = forms.CharField(max_length=100, widget=forms.PasswordInput)


class formNuevaCompraPresupuesto(forms.Form):
    presupuesto = forms.FloatField()


class formNuevaCompraIngresada(forms.Form):
    producto = forms.CharField(max_length=255)

class formNuevaCompraCantidad(forms.Form):
    cantidad = forms.IntegerField()

class formRegistroUsuario(forms.Form):
    nombre = forms.CharField(max_length=255)
    barrio = forms.CharField(max_length=255)
    direccion = forms.CharField(max_length=255)
    constrasena = forms.CharField(max_length=255)

desarrolloSmartApp/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import HttpResponse
from .forms import *

from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.forms import ModelForm 
from django.contrib.auth.models import User
from django import forms
from django.contrib import messages

nombre = ""
compras = 0
idProducto = []
cantidadCompra = []
precioUnitario = []
excesoDeCompra = ""

def paginaLogin(request):
        return render (request, 'recursosHTML/index.html')

def login(request):
                global nombre

                email = ""
                contrasena = ""
                redireccionarEmail = False
                redireccionarContrasena = False
                
                if request.POST["Email"]:
                        email = request.POST["Email"]
                        if not(Usuario.objects.filter(email=email).count()):
                                errorEmail = "El usuario ingresado es incorrecto"
                                return render(request, 'recursosHTML/index.html', 
                                                { "errorEmail":errorEmail })
                        else:
                                redireccionarEmail = True
                if request.POST["Contraseña"]:
                        contrasena = request.POST["Contraseña"]
                        if not(Usuario.objects.filter(email = email, 
                                                        contrasena=contrasena).count()):
                                 errorContrasena = "La contarseña ingresada es incorrecta"
                                 return render(request, 'recursosHTML/index.html', 
                                                { "errorContrasena":errorContrasena })
                        else:
                                redireccionarContrasena = True

                if redireccionarEmail and redireccionarContrasena:
                        nombre = email
                        usuario = Usuario.objects.filter(email=nombre)
                        nombrePersonaLogueada = usuario[0].nombre
                        apellidoPersonaLogueada = usuario[0].apellido

                        context = {
                                        "nombrePersonaLogueada":nombrePersonaLogueada,
                                        "apellidoPersonaLogueada":apellidoPersonaLogueada
                        }    
                        return render (request, 'recursosHTML/Principal.html', context)

                errorEmail = "Ingrese su usuario"
                errorContrasena = "Ingrese su contraseña"
                return render(request, 'recursosHTML/index.html', 
                                {  "errorEmail":errorEmail,
                                "errorContrasena":errorContrasena })
        
        
       
         
def principal(request):
        global nombre 
        usuario = Usuario.objects.filter(email=nombre)
        nombrePersonaLogueada = usuario[0].nombre
        apellidoPersonaLogueada = usuario[0].apellido

        context = {
                                "nombrePersonaLogueada":nombrePersonaLogueada,
                                "apellidoPersonaLogueada":apellidoPersonaLogueada
                  }    
        return render (request, 'recursosHTML/Principal.html', context)


def nuevaCompra(request):
        nuevaCompraPresupuesto = formNuevaCompraPresupuesto(request.POST or None)
        nuevaCompraIngresada = formNuevaCompraIngresada(request.POST or None)
        nuevaCompraCantidad = formNuevaCompraCantidad(request.POST or None)
        productos = Producto.objects.all()
        

        if nuevaCompraIngresada.is_valid() and nuevaCompraCantidad.is_valid():
                nuevaCompraCantidad_data = nuevaCompraCantidad.cleaned_data
                nuevaCompraIngresada_data = nuevaCompraIngresada.cleaned_data
                producto = nuevaCompraIngresada_data.get("producto")
                cantidad = nuevaCompraCantidad_data.get("cantidad")
                if not(Producto.objects.filter(id = producto).count()):
                        nuevaCompraIngresada.add_error("producto",'Este producto no esta en la lista')
                        

        if nuevaCompraPresupuesto.is_valid():
                nuevaCompraPresupuesto_data = nuevaCompraPresupuesto.cleaned_data
                presupuesto = nuevaCompraPresupuesto_data.get("presupuesto")
                global compras 
                global idProducto
                global cantidadCompra
                global precioUnitario
                global excesoDeCompra
                
                if Producto.objects.filter(id = producto).count() and presupuesto < (compras + (Producto.objects.get(id = producto).precio * cantidad)):
                        excesoDeCompra = 'El monto total de la compra excede el presupuesto ingresado'
                        nuevaCompraPresupuesto.add_error("presupuesto", 'El monto total de la compra excede el presupuesto ingresado')
                else:
                        if Producto.objects.filter(id = producto).count():
                                compras = compras + (Producto.objects.get(id = producto).precio * cantidad)
                                idProducto.append(producto)
                                cantidadCompra.append(cantidad)
                                precioUnitario.append(Producto.objects.get(id = producto).precio)
                                nuevaCompraPresupuesto.add_error("presupuesto", 'Monto actual de la compra: $' + str(compras))
        global nombre 
        usuario = Usuario.objects.filter(email=nombre)
        nombrePersonaLogueada = usuario[0].nombre
        apellidoPersonaLogueada = usuario[0].apellido     
        
        context = {
                "formNuevaCompraPresupuesto":nuevaCompraPresupuesto,
                "formNuevaCompraIngresada":nuevaCompraIngresada,
                "formNuevaCompraCantidad":nuevaCompraCantidad,
                'productos':productos,
                "nombrePersonaLogueada":nombrePersonaLogueada,
                "apellidoPersonaLogueada":apellidoPersonaLogueada
        }
        
        return render (request, 'recursosHTML/NuevaCompra.html',context)

def paginaRegistro(request):
        return render (request, 'recursosHTML/Registro.html')

def registro(request):
        if request.POST['usuario']:
                usuario = request.POST['usuario']

        if request.POST['apellido']:
                apellido = request.POST['apellido']

        if request.POST['seleccionSexo']:
                seleccionSexo = str(request.POST['seleccionSexo'])

        if request.POST['nacimiento']:
                nacimiento = request.POST['nacimiento']
        
        if request.POST['barrio']:
                barrio = request.POST['barrio']

        if request.POST['direccion']:
                direccion = request.POST['direccion']

        if request.POST['email']:
                controlEmail = request.POST['email']

                if Usuario.objects.filter(email = controlEmail).count():
                        errorEmail = "El email ingresado ya existe"
                        return render(request, 'recursosHTML/Registro.html', {'errorEmail':errorEmail})
                if '@' in controlEmail:
                        email = request.POST['email']
                else:
                        errorEmail = "El email ingresado debe poseer el caracter @"
                        return render(request, 'recursosHTML/Registro.html', {'errorEmail':errorEmail})
               

        if request.POST['contrasena1'] and request.POST['contrasena2']:
                controlContrasena = request.POST['contrasena1']

                if len(controlContrasena) < 6:
                        errorContrasenas = "Su contraseña debe ser mayor de 6 caracteres"
                        return render(request, 'recursosHTML/Registro.html', {'errorContrasenas':errorContrasenas})

                if not(request.POST['contrasena1'] == request.POST['contrasena2']):
                        errorContrasenas = "Contraseñas inválidas"
                        return render(request, 'recursosHTML/Registro.html', {'errorContrasenas':errorContrasenas})

                contrasena = request.POST['contrasena1']
                
        
        
        Usuario.objects.create(nombre=usuario, apellido=apellido, seleccionSexo=seleccionSexo,
                        nacimiento=nacimiento, barrio=barrio, direccion=direccion, 
                        email=email, contrasena=contrasena)
        
        
        return render(request, 'recursosHTML/index.html')
        
def terminarCompra(request):
        global nombre
        global compras
        global idProducto
        global cantidadCompra
        global precioUnitario
        global excesoDeCompra 

        usuario = Usuario.objects.filter(email=nombre)
        nombrePersonaLogueada = usuario[0].nombre
        apellidoPersonaLogueada = usuario[0].apellido

        if not(compras == 0): 
                Compra.objects.create(idUsuario = Usuario.objects.filter(email = nombre)[0], monto_compra = compras)

                idCompraUltimo = Compra.objects.latest('id')
                for idx, val in enumerate(idProducto):
                        Item.objects.create(idCompra = idCompraUltimo, idProducto = Producto.objects.get(id = idProducto[idx]), cantidad = cantidadCompra[idx], precioUnitario = precioUnitario[idx])

        compras = 0
        precioUnitario = []
        idProducto = []
        cantidadCompra = []
        

        context = {
                        "nombrePersonaLogueada":nombrePersonaLogueada,
                        "apellidoPersonaLogueada":apellidoPersonaLogueada
                  }   
        return render(request, 'recursosHTML/TerminarCompra.html', context)

def tarjDebitoCredito(request):
        if request.POST['tarjeta']:

desarrolloSmartApp/templates/recursosHTML/DireccionAplicacion.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'diseñoSmart/css/smartpurchase.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
        crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>

</head>

<body>
    </br>
    </br>
    <!-- Page Content Holder -->
    <div id="content" class="container-fluid">
        <div class="mx-auto d-block">
            <div class="row justify-content-center">
                <div class='col-xs-12 col-sm-6 col-md-5'>
                    <h3 class="text-center">Para ir al sitio SmartPurchase presione el boton que se encuentra debajo.</h3>
                </div>
            </div>
        </div>
        </br>
        </br>
        </br>
        <div class="mx-auto d-block">
            <div class="row justify-content-center">
                <div class='col-xs-12 col-sm-6 col-md-5'>
                    <button type="button" class="btn btn-success mx-auto d-block btn-lg btn-block" id="registrarseBtn"
                        onClick="window.location.href='desarrolloSmartApp/index.html'">Ir al sitio</button>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>

</html>

desarrolloSmartApp/templates/recursosHTML/Menu.html
{% load static %}
<!DOCTYPE html>
<html>
    <body>
        <nav class="d-flex" style="background-color: #5b9e6a;">
            <div class="navbar-nav mr-auto mt-2 ml-2">
                <div class="dropdown">
                    <!--<h5 style = "color:white">Usuario: {{nombrePersonaLogueada}} {{apellidoPersonaLogueada}}</h5>-->
                    <button class="btn btn-success btn-lg btn-responsive dropdown-toggle" type="button"
                        id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true">{{nombrePersonaLogueada}} {{apellidoPersonaLogueada}}</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="NuevaCompra.html" style="color: black">Nueva compra</a>
                        <a class="dropdown-item" href="./" style="color: black">Historico de compras</a>
                        <a class="dropdown-item" href="#" style="color: black">Consulta de precio</a>
                        <a class="dropdown-item" href="#" style="color: black">Consulta de producto</a>
                        <a class="dropdown-item" href="index.html" style="color: black">Salir</a>
                    </div>
                </div>
            </div>
            <image src="{% static 'diseñoSmart/imagenes/logo.png' %}" class="img-fluid right-block" alt="Responsive image"
                width="70" height="70"></image>
        </nav>
    </body>
</html>

desarrolloSmartApp/templates/recursosHTML/NuevaCompra.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'diseñoSmart/css/smartpurchase.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
        crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>

</head>

<body>
    {%include "recursosHTML/Menu.html"%}
    </br>
    </br>
    <!-- Page Content Holder -->
    <div id="content" class="container-fluid">
        <div class="form-group mx-auto d-block">
            <div class="row justify-content-center">
                <div class='col-xs-12 col-sm-12 col-md-8'>
                    <form method="POST" action="">{% csrf_token %}
                        <div class="form-group col-8 mx-auto d-block">
                            <div class="form-control" id="presupuestoMax">
                                {{formNuevaCompraPresupuesto}}
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-highlight">
                                <thead>
                                    <th>Cod prod</th>
                                    <th>Artículo</th>
                                    <th>Precio</th>
                                    <th>Imagen</th>
                                    <th>Comprar</th>
                                </thead>
                                <tbody>
                                    {% for producto in productos %}
                                    <tr>
                                        <td>{{producto.id}}</td>
                                        <td>{{producto.nombre}}</td>
                                        <td>{{producto.precio}}</td>
                                        <td><img src="/{{producto.imagen}}" style='width: 80px; height: 80;'/></td>
                                        <td><button onclick="displayFoto('{{producto.imagen}}','{{producto.id}}')" type="button" data-toggle="modal" data-target="#mi-modal" class="btn btn-success">Seleccionar</button></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="modal" id="mi-modal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header"> 
                                        <h5 class="modal-title">Confirmar agregar producto</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        <div class="form-group col-12 mx-auto d-block">
                                            <div class="form-control" id="imagenProd" >
                                                <img id='imagenDetallePrducto' href='' class="form-group col-12 mx-auto d-block" style="height: 330px;"/>
                                            </div>
                                          </div>
                                        <div style="display: none;">
                                            <div id="listaCompras">
                                                {{formNuevaCompraIngresada}}
                                            </div>
                                        </div>
                                        <div class="form-group col-12 mx-auto d-block">
                                            <div class="form-control">
                                                {{formNuevaCompraCantidad}}
                                            </div>
                                      </div>
                                      
                                      <div class="form-group col-8 mx-auto d-block custom-control custom-checkbox">
                                        <input type="submit" class="btn btn-success" value="Comprar" />
                                    </div>
                                    </div>
                                </div>
                            </div>
                            
                            </div>
                        
                        
                    </form>
                    <form method="POST" action="TerminarCompra.html">{% csrf_token %}
                        <div class="form-group col-8 mx-auto d-block custom-control custom-checkbox">
                            <input type="submit" class="btn btn-success" value="Terminar compra" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
        function displayFoto(url,valueProd)
        {
            console.log("entro")
            console.log(url);
            document.getElementById("imagenDetallePrducto").setAttribute("src", "/"+url.toString());
            $('#id_producto').val(valueProd)
        }
    </script>
</body>

</html>

desarrolloSmartApp/templates/recursosHTML/TerminarCompra.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'diseñoSmart/css/smartpurchase.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
        crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>

</head>

<body>
    {%include "recursosHTML/Menu.html"%}
    </br>
    </br>
    <!-- Page Content Holder -->
    <div id="content" class="container-fluid">
        <div class="mx-auto d-block">
            <div class="row justify-content-center">
                <div class='col-xs-12 col-sm-6 col-md-5'>
                    <h3 class="text-center">¿Cómo quieres pagar?</h3>
                </div>
            </div>
        </div>
        </br>
        </br>
        </br>
        <div class="mx-auto d-block">
            <div class="row justify-content-center">
                <div class='col-xs-12 col-sm-6 col-md-5'>
                    <button type="button" class="btn btn-success mx-auto d-block btn-lg btn-block" id="registrarseBtn"
                        onClick="window.location.href='./TarjDebitoCredito.html'">Añadir tarjeta de débito o crédito</button>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>

</html>